name: dompetdhuafaconceptmodul4
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter_svg: ^2.0.7
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  fancy_shimmer_image: ^2.0.3
  http: ^1.1.0
  webview_flutter: ^4.4.1
  firebase_core: ^2.21.0
  firebase_auth: ^4.12.1
  google_sign_in: ^6.1.5

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/svgs/
